#!/bin/sh

#************* Configuration **************

#Set the MIGRATION_PATH to the directory where you store all the *{up,down}.sql files
MIGRATION_PATH="migrations"

#Set the script where the sql queries should be piped to, for example:
#OUTPUT="mysql --host=127.0.0.1 --user=root --password=mypassword --database=mydatabase"
#defaults to show only:
#OUTPUT="cat"
OUTPUT="cat"

#********** End of configuration **********

oldref=$1
newref=$2
flag=$3
 
if [ $flag -eq 0 ]; then
	exit 0
fi

for ref in `git rev-list $newref..$oldref`; do
	tree=`git cat-file commit $ref | head -n1 | cut -f2 -d' '`
	IFS=" \t" git cat-file -p $tree | while read perms type sha path; do
		if [ "$path" = $MIGRATION_PATH ]; then
			IFS=" \t" git cat-file -p $sha | grep down.sql\$ | sort -r -k2 | while read p t s f; do
				echo "-- $f"
				git cat-file -p $s | $OUTPUT
			done
		fi
	done
done
for ref in `git rev-list --reverse $oldref..$newref`; do
	tree=`git cat-file commit $ref | head -n1 | cut -f2 -d' '`
	IFS=" \t" git cat-file -p $tree | while read perms type sha path; do
		if [ "$path" = $MIGRATION_PATH ]; then
			IFS=" \t" git cat-file -p $sha | grep up.sql\$ | sort -k2 | while read p t s f; do
				echo "-- $f"
				git cat-file -p $s | $OUTPUT
			done
		fi
	done
done
