#!/bin/sh

#This git-migration-hook originated from https://github.com/richardbrinkman/git-migration-hook
#where you can find the newest version. If you have an improved version, feel free to generate
#a pull request.

#************* Configuration **************

#Set the MIGRATION_PATH to the directory where you store all the *{up,down}.sql files
MIGRATION_PATH="migrations"

#Set the script where the sql queries should be piped to, for example:
#OUTPUT="mysql --host=127.0.0.1 --user=root --password=mypassword --database=mydatabase"
#defaults to show only:
#OUTPUT="cat"
OUTPUT="cat"

#********** End of configuration **********

oldref=$1
newref=$2
flag=$3
 
if [ $flag -eq 0 ]; then
	exit 0
fi

for ref in `git rev-list $newref..$oldref`; do
	git show --pretty=oneline --name-only $ref | tail -n +2 | grep ^$MIGRATION_PATH | grep down.sql\$ | sort -r | while read file; do
		echo "--" $file
		git show $ref:$file | $OUTPUT
	done
done
for ref in `git rev-list --reverse $oldref..$newref`; do
	git show --pretty=oneline --name-only $ref | tail -n +2 | grep ^$MIGRATION_PATH | grep up.sql\$ | sort | while read file; do
		echo "--" $file
		git show $ref:$file | $OUTPUT
	done
done
